ids_file_name = "data/objects_ids.txt"
migrated_ids_file_name = "data/migrated_objects_ids.txt"
not_fully_migrated_ids_file_name = "data/not_fully_migrated_objects_ids.txt"
img_error_file_name = "data/missing_images.txt"
collection_space = "your-address-to-collectionspace"
cspace_services = collection_space + "/cspace-services"